org.quartz.scheduler.instanceName=SchedulerLocal
org.quartz.scheduler.instanceId=AUTO

org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount=5
org.quartz.threadPool.threadPriority=5

org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
org.quartz.jobStore.useProperties=false
org.quartz.jobStore.tablePrefix=QRTZ_
org.quartz.jobStore.dataSource=quartzDataSource
org.quartz.jobStore.isClustered=false
org.quartz.jobStore.misfireThreshold=60000

org.quartz.dataSource.quartzDataSource.driver=org.h2.Driver
org.quartz.dataSource.quartzDataSource.URL=jdbc:h2:file:./data/quartz-db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
org.quartz.dataSource.quartzDataSource.user=sa
org.quartz.dataSource.quartzDataSource.password=
org.quartz.dataSource.quartzDataSource.maxConnections=10
